//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/_Script/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""VR"",
            ""id"": ""fa31024a-c3ea-4f81-a3d8-57239ace8853"",
            ""actions"": [
                {
                    ""name"": ""Grip"",
                    ""type"": ""Button"",
                    ""id"": ""07f99a56-9410-40f1-b0e7-77e675d627ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gas"",
                    ""type"": ""Button"",
                    ""id"": ""2858d25d-df05-4e5d-8822-2d4430ae2620"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Break"",
                    ""type"": ""Button"",
                    ""id"": ""53205ad5-7a07-4635-825c-785c81bbbd5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L_X"",
                    ""type"": ""Button"",
                    ""id"": ""7e1de6a7-6adb-4908-b92a-5ecfad08df32"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2eebe9a3-3213-417b-abd8-466222c0691c"",
                    ""path"": ""<OculusTouchController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0a14cd6-adcc-4162-b595-a74f24b0a5e4"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""141964c5-1bac-46a4-99de-14a26c38257d"",
                    ""path"": ""<OculusTouchController>/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef3af4b5-6f8e-479e-a9e0-7ec27f8a9767"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8342603-2810-456c-a98d-bba7bd2278ce"",
                    ""path"": ""<OculusTouchController>/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Break"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6da3077a-6f23-47d7-8177-846424401013"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Break"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcf15b71-479f-4fa8-9322-770f85be13fb"",
                    ""path"": ""<OculusTouchController>/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L_X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78a4799d-710f-476d-bd5a-74730f878676"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L_X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VR
        m_VR = asset.FindActionMap("VR", throwIfNotFound: true);
        m_VR_Grip = m_VR.FindAction("Grip", throwIfNotFound: true);
        m_VR_Gas = m_VR.FindAction("Gas", throwIfNotFound: true);
        m_VR_Break = m_VR.FindAction("Break", throwIfNotFound: true);
        m_VR_L_X = m_VR.FindAction("L_X", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VR
    private readonly InputActionMap m_VR;
    private IVRActions m_VRActionsCallbackInterface;
    private readonly InputAction m_VR_Grip;
    private readonly InputAction m_VR_Gas;
    private readonly InputAction m_VR_Break;
    private readonly InputAction m_VR_L_X;
    public struct VRActions
    {
        private @PlayerControls m_Wrapper;
        public VRActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Grip => m_Wrapper.m_VR_Grip;
        public InputAction @Gas => m_Wrapper.m_VR_Gas;
        public InputAction @Break => m_Wrapper.m_VR_Break;
        public InputAction @L_X => m_Wrapper.m_VR_L_X;
        public InputActionMap Get() { return m_Wrapper.m_VR; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VRActions set) { return set.Get(); }
        public void SetCallbacks(IVRActions instance)
        {
            if (m_Wrapper.m_VRActionsCallbackInterface != null)
            {
                @Grip.started -= m_Wrapper.m_VRActionsCallbackInterface.OnGrip;
                @Grip.performed -= m_Wrapper.m_VRActionsCallbackInterface.OnGrip;
                @Grip.canceled -= m_Wrapper.m_VRActionsCallbackInterface.OnGrip;
                @Gas.started -= m_Wrapper.m_VRActionsCallbackInterface.OnGas;
                @Gas.performed -= m_Wrapper.m_VRActionsCallbackInterface.OnGas;
                @Gas.canceled -= m_Wrapper.m_VRActionsCallbackInterface.OnGas;
                @Break.started -= m_Wrapper.m_VRActionsCallbackInterface.OnBreak;
                @Break.performed -= m_Wrapper.m_VRActionsCallbackInterface.OnBreak;
                @Break.canceled -= m_Wrapper.m_VRActionsCallbackInterface.OnBreak;
                @L_X.started -= m_Wrapper.m_VRActionsCallbackInterface.OnL_X;
                @L_X.performed -= m_Wrapper.m_VRActionsCallbackInterface.OnL_X;
                @L_X.canceled -= m_Wrapper.m_VRActionsCallbackInterface.OnL_X;
            }
            m_Wrapper.m_VRActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Grip.started += instance.OnGrip;
                @Grip.performed += instance.OnGrip;
                @Grip.canceled += instance.OnGrip;
                @Gas.started += instance.OnGas;
                @Gas.performed += instance.OnGas;
                @Gas.canceled += instance.OnGas;
                @Break.started += instance.OnBreak;
                @Break.performed += instance.OnBreak;
                @Break.canceled += instance.OnBreak;
                @L_X.started += instance.OnL_X;
                @L_X.performed += instance.OnL_X;
                @L_X.canceled += instance.OnL_X;
            }
        }
    }
    public VRActions @VR => new VRActions(this);
    public interface IVRActions
    {
        void OnGrip(InputAction.CallbackContext context);
        void OnGas(InputAction.CallbackContext context);
        void OnBreak(InputAction.CallbackContext context);
        void OnL_X(InputAction.CallbackContext context);
    }
}
